sudo: false
language: python
python:
- '2.7'
install:
- pip install pygments lxml setuptools --upgrade
- git clone https://github.com/tabatkins/bikeshed.git
- pip install --editable $PWD/bikeshed
- bikeshed update
script:
- bash "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: "2fd5a6f59c4a"
  - COMMIT_AUTHOR_EMAIL: "eyaich@chromium.org"
